export type ILyricsRow = Record<string, boolean | undefined>;

export interface ISong {
    author: string;
    name: string;
    chords: string[];
    lyrics: string[][];
    speed?: number;
}

export const CHORDS_ROW = 'chords_row';

export const Songs: ISong[] = [
    {
        author: 'Ночные снайперы',
        name: 'Асфальт',
        chords: ['A', 'A#', 'A7', 'Dm', 'F', 'Cm', 'C#', 'Gm', 'G#'],
        lyrics: [
            ['Dm', CHORDS_ROW],
            ['В газетах писали, что ты уезжаешь,'],
            ['     A#                   F', CHORDS_ROW],
            ['Что рейс не отменят, что рейс не отложат.'],
            ['   Dm', CHORDS_ROW],
            ['Какие-то люди тебя окружают,'],
            ['    A#               F', CHORDS_ROW],
            ['А ближе, чем были, уже невозможно.'],
            ['\n'],
            ['      Gm', CHORDS_ROW],
            ['В красивых журналах считают пунктиры,'],
            ['  Cm', CHORDS_ROW],
            ['А я до квартиры - вечернее сальто.'],
            ['    G#', CHORDS_ROW],
            ['И кривятся губы, и кофе противен.'],
            ['   C#           A', CHORDS_ROW],
            ['И новое утро и новое "нет тебя".'],
            ['\n'],
            ['Припев:'],
            ['     A# A7   Dm       A#', CHORDS_ROW],
            ['     Я по асфальту шагаю'],
            ['        Gm     A7    Dm         A#', CHORDS_ROW],
            ['     С тем, кого сберечь не смогу.'],
            ['     Gm A7   Dm        A#', CHORDS_ROW],
            ['     До остановки трамвая,'],
            ['         Gm     A7   Dm', CHORDS_ROW],
            ['     Звенящего на бегу.'],
            ['\n'],
            ['Dm', CHORDS_ROW],
            ['В газетах писали, что ты идиотка,'],
            ['     A#               F', CHORDS_ROW],
            ['Во всем виновата проклятая водка.'],
            ['   Dm', CHORDS_ROW],
            ['Ругаешься матом и песен не пишешь.'],
            ['   A#             F', CHORDS_ROW],
            ['Тебя окружают не люди, а мыши.'],
            ['\n'],
            ['      Gm', CHORDS_ROW],
            ['В красивых журналах считают пунктиры -'],
            ['   Cm', CHORDS_ROW],
            ['Такое не выдумать даже нарочно.'],
            ['  G#', CHORDS_ROW],
            ['А я каждый вечер ползу до квартиры.'],
            ['    C#             A', CHORDS_ROW],
            ['И ближе, чем были, уже невозможно.'],
            ['\n'],
            ['Припев:'],
            ['     A# A7   Dm       A#', CHORDS_ROW],
            ['     Я по асфальту шагаю'],
            ['        Gm     A7    Dm         A#', CHORDS_ROW],
            ['     С тем, кого сберечь не смогу.'],
            ['     Gm A7   Dm        A#', CHORDS_ROW],
            ['     До остановки трамвая,'],
            ['         Gm     A7   Dm', CHORDS_ROW],
            ['     Звенящего на бегу.'],
            ['\n'],
            ['     A# A7   Dm       A#', CHORDS_ROW],
            ['     Я по асфальту шагаю'],
            ['        Gm     A7    Dm         A#', CHORDS_ROW],
            ['     С тем, кого сберечь не смогу.'],
            ['     Gm A7   Dm        A#', CHORDS_ROW],
            ['     До остановки трамвая,'],
            ['         Gm     A7   Dm', CHORDS_ROW],
            ['     Звенящего на бегу.'],
            ['\n'],
        ],
    },
];
